# Generated by Django 3.1.3 on 2021-05-08 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_Name', models.CharField(default=None, max_length=200)),
                ('Start_Year', models.DateTimeField(default=None, verbose_name='Start Year')),
                ('End_Year', models.DateTimeField(default=None, verbose_name='End Year')),
                ('GPA', models.FloatField(default=0.0)),
                ('Transcript_Link', models.URLField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(default=None, max_length=200)),
                ('URL_Link', models.URLField(default=None)),
                ('Active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skill_Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill_Parent_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Source_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source_Type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Achievement_Name', models.CharField(default=None, max_length=200)),
                ('Achievement_Desc', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc_Name', models.CharField(default=None, max_length=200)),
                ('Desc_Desc', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Work_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Title', models.CharField(default=None, max_length=200)),
                ('Start_Year', models.DateTimeField(default=None, verbose_name='Start Year')),
                ('End_Year', models.DateTimeField(default=None, verbose_name='End Year')),
                ('Present_Job', models.BooleanField(default=False)),
                ('Phone_Number', models.IntegerField(default=None)),
                ('Job_Desc', models.ManyToManyField(to='General.Work_Description')),
                ('Work_Achiv', models.ManyToManyField(to='General.Work_Achievements')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill_Name', models.CharField(max_length=200)),
                ('Years_Of_Exp', models.IntegerField(default=0)),
                ('Education_Key', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.education')),
                ('Job_Key', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.work_history')),
                ('Source_Type', models.ManyToManyField(default=None, to='General.Source_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference_Name', models.CharField(default=None, max_length=200)),
                ('Reference_Number', models.IntegerField(default=None)),
                ('Education_Key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='General.education')),
                ('Job_Key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='General.work_history')),
                ('Source_Type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='General.source_type')),
            ],
        ),
    ]
