# Generated by Django 3.1.3 on 2021-05-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='Skill_Desc',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
